{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pubs.sdk",
    "module": "pubsdk",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "pubsdk-1.3.4.aar",
          "url": "pubsdk-1.3.4.aar",
          "size": 254706,
          "sha512": "e1791dd6116b617f444b0fa7630f5f52691fdb43c9a9fd676d12c334978e0a8051252bb2ac4f69464cae58b3b29f3283383d4eafcfbaba714cee5882276c5ff9",
          "sha256": "95b481c4e8793bb69111c6e5d30892ba38ba21713ce3b40f47002d931330d5e3",
          "sha1": "477bdbb255960ccf5a0c2129b99cdae6370fb8e3",
          "md5": "88c4cb64aad710f56c209489a5234ee1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.4.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-adapter",
          "version": {
            "requires": "24.4.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-ad-manager-adapter",
          "version": {
            "requires": "24.4.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-ad-manager-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.14.3.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.3.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.14.3.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "applovin",
          "version": {
            "requires": "13.3.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "applovin",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "14.3.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.14.3.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.14.3.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "bigo-ads",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "bigoads-adapter",
          "version": {
            "requires": "5.3.0.2"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-bigo",
          "version": {
            "requires": "57.14.3.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "admob-mediation",
          "version": {
            "requires": "5.3.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "admob-mediation",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "pubsdk-1.3.4.aar",
          "url": "pubsdk-1.3.4.aar",
          "size": 254706,
          "sha512": "e1791dd6116b617f444b0fa7630f5f52691fdb43c9a9fd676d12c334978e0a8051252bb2ac4f69464cae58b3b29f3283383d4eafcfbaba714cee5882276c5ff9",
          "sha256": "95b481c4e8793bb69111c6e5d30892ba38ba21713ce3b40f47002d931330d5e3",
          "sha1": "477bdbb255960ccf5a0c2129b99cdae6370fb8e3",
          "md5": "88c4cb64aad710f56c209489a5234ee1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
