{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pubs.sdk",
    "module": "pubsdk",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "pubsdk-1.2.2.aar",
          "url": "pubsdk-1.2.2.aar",
          "size": 248122,
          "sha512": "0eec37557b03a913808531c86380cf4a2f38bb319ef1b4225971e2be3497accf60157436bb4f2a21d43cde5b3f058d8c5794ee309404574a8e6cec6dd34d34c3",
          "sha256": "0c346c53efd722efcf6b1708d228f74ac7403ab950fba41212ff458e73332baa",
          "sha1": "1986dca5fc483d1b1e3fab19717717091da83663",
          "md5": "2e9fee519fd1b815bac20b3088719812"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-adapter",
          "version": {
            "requires": "24.1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-ad-manager-adapter",
          "version": {
            "requires": "24.1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-ad-manager-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.13.8.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.2.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.13.8.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "applovin",
          "version": {
            "requires": "13.2.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "applovin",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "13.8.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.13.8.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.13.8.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "bigo-ads",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "bigoads-adapter",
          "version": {
            "requires": "5.2.1.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-bigo",
          "version": {
            "requires": "57.13.8.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "admob-mediation",
          "version": {
            "requires": "5.2.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "admob-mediation",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "pubsdk-1.2.2.aar",
          "url": "pubsdk-1.2.2.aar",
          "size": 248122,
          "sha512": "0eec37557b03a913808531c86380cf4a2f38bb319ef1b4225971e2be3497accf60157436bb4f2a21d43cde5b3f058d8c5794ee309404574a8e6cec6dd34d34c3",
          "sha256": "0c346c53efd722efcf6b1708d228f74ac7403ab950fba41212ff458e73332baa",
          "sha1": "1986dca5fc483d1b1e3fab19717717091da83663",
          "md5": "2e9fee519fd1b815bac20b3088719812"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
